Repository WildCodeSchool/orleans-php-2003-project-easterapp, pull requests merged in 2020-06, with the labels that each got.

#8 bootstrap and jquery added
  assets/js/app.js
  assets/scss/app.scss
  package.json
  src/Controller/HomeController.php
  templates/home/index.html.twig
  yarn.lock
Labels: reviewed

#16 S01US00 navbar template
  assets/scss/_vars.scss
  assets/scss/app.scss
  assets/scss/navbar.scss
  templates/base.html.twig
  templates/parts/_navbar.html.twig
Labels: reviewed

#15 S01 us03 project details
  assets/scss/_vars.scss
  assets/scss/app.scss
  assets/scss/projectDetails.scss
  src/Controller/ProjectController.php
  src/Entity/Project.php
  src/Form/ProjectType.php
  src/Repository/ProjectRepository.php
  templates/project/_delete_form.html.twig
  templates/project/_form.html.twig
  templates/project/edit.html.twig
  templates/project/index.html.twig
  templates/project/new.html.twig
  templates/project/show.html.twig
Labels: corrections done, reviewed

#19 S01US38_Edit_Project_Application
  assets/scss/app.scss
  assets/scss/projectDetails.scss
  src/Entity/Application.php
  src/Entity/Project.php
  src/Form/ProjectType.php
  src/Repository/ApplicationRepository.php
  templates/base.html.twig
  templates/project/_form.html.twig
Labels: reviewed

#20 S01 us00_resolved_conflict_navbar
  assets/scss/_vars.scss
  assets/scss/app.scss
  assets/scss/navbar.scss
  templates/base.html.twig
  templates/parts/_navbar.html.twig
Labels: corrections done, reviewed

#27 Dev to master
  assets/js/app.js
  assets/scss/_vars.scss
  assets/scss/app.scss
  assets/scss/navbar.scss
  assets/scss/projectDetails.scss
  package.json
  src/Controller/FeatureController.php
  src/Controller/HomeController.php
  src/Controller/ProjectController.php
  src/Entity/Application.php
  src/Entity/Category.php
  src/Entity/Feature.php
  src/Entity/Project.php
  src/Form/ProjectType.php
  src/Repository/ApplicationRepository.php
  src/Repository/CategoryRepository.php
  src/Repository/FeatureRepository.php
  src/Repository/ProjectRepository.php
  templates/base.html.twig
  templates/feature/index.html.twig
  templates/home/index.html.twig
  templates/parts/_navbar.html.twig
  templates/project/_delete_form.html.twig
  templates/project/_form.html.twig
  templates/project/edit.html.twig
  templates/project/index.html.twig
  templates/project/new.html.twig
  templates/project/show.html.twig
  yarn.lock
Labels: reviewed

#49 S01US01_project_list
  templates/project/index.html.twig
Labels: reviewed

#50 FIX_Navbar
  assets/scss/navbar.scss
  templates/parts/_navbar.html.twig
  webpack.config.js
Labels: reviewed

#30 S01 us39 edit project feature list
  assets/fonts/_H_HelveticaNeueInterface_2.ttf
  assets/scss/_vars.scss
  assets/scss/app.scss
  assets/scss/projectDetails.scss
  composer.json
  composer.lock
  config/bundles.php
  config/services.yaml
  src/DataFixtures/ApplicationFixtures.php
  src/DataFixtures/CategoryFixtures.php
  src/DataFixtures/FeatureFixtures.php
  src/DataFixtures/ProjectFeatureFixtures.php
  src/DataFixtures/ProjectFixtures.php
  src/Entity/Feature.php
  src/Entity/Project.php
  src/Entity/ProjectFeature.php
  src/Form/ProjectFeatureType.php
  src/Form/ProjectType.php
  src/Repository/ProjectFeatureRepository.php
  symfony.lock
  templates/project/_featuresList.html.twig
  templates/project/_form.html.twig
  templates/project/edit.html.twig
  webpack.config.js
Labels: corrections done, reviewed

#51 S02US40_TotalLoadCalculation
  assets/scss/app.scss
  assets/scss/projectDetails.scss
  src/Controller/ProjectController.php
  src/Service/ProjectCalculator.php
  templates/project/_form.html.twig
Labels: reviewed

#53 S01toMASTER_RemainingUS
  assets/fonts/_H_HelveticaNeueInterface_2.ttf
  assets/scss/_vars.scss
  assets/scss/app.scss
  assets/scss/navbar.scss
  assets/scss/projectDetails.scss
  composer.json
  composer.lock
  config/bundles.php
  config/services.yaml
  src/Controller/ProjectController.php
  src/DataFixtures/ApplicationFixtures.php
  src/DataFixtures/CategoryFixtures.php
  src/DataFixtures/FeatureFixtures.php
  src/DataFixtures/ProjectFeatureFixtures.php
  src/DataFixtures/ProjectFixtures.php
  src/Entity/Feature.php
  src/Entity/Project.php
  src/Entity/ProjectFeature.php
  src/Form/ProjectFeatureType.php
  src/Form/ProjectType.php
  src/Repository/ProjectFeatureRepository.php
  src/Service/ProjectCalculator.php
  symfony.lock
  templates/parts/_navbar.html.twig
  templates/project/_featuresList.html.twig
  templates/project/_form.html.twig
  templates/project/edit.html.twig
  templates/project/index.html.twig
  webpack.config.js
Labels: reviewed

#52 S02US09_deleteProjectFeature
  assets/scss/app.scss
  src/Controller/ProjectController.php
  templates/project/_featuresList.html.twig
Labels: corrections done, reviewed

#55 S02US12_showFeatureCategoryInProjectDetails
  src/DataFixtures/ProjectFeatureFixtures.php
  src/Entity/ProjectFeature.php
  src/Form/ProjectFeatureType.php
  templates/project/_featuresList.html.twig
Labels: reviewed

#61 S02US20_add feature
  src/Controller/FeatureController.php
  src/Form/FeatureType.php
  templates/feature/_delete_form.html.twig
  templates/feature/_form.html.twig
  templates/feature/index.html.twig
  templates/feature/new.html.twig
  templates/feature/show.html.twig
Labels: corrections done, reviewed

#62 S02US04_delete_project
  templates/project/_delete_form.html.twig
  templates/project/edit.html.twig
  templates/project/index.html.twig
Labels: reviewed

#69 S02US21_ EDIT FEATURES
  templates/feature/_form.html.twig
  templates/feature/edit.html.twig
Labels: reviewed

#74 Fix_projectFeatureFixtures
  src/DataFixtures/ProjectFeatureFixtures.php
Labels: ImportantFix, reviewed

#64 S02 us02 create new project
  assets/scss/newProject.scss
  composer.lock
  src/Controller/ProjectController.php
  symfony.lock
  templates/project/_form.html.twig
  templates/project/edit.html.twig
  templates/project/index.html.twig
  templates/project/new.html.twig
  webpack.config.js
Labels: corrections done, reviewed

#75 S02DEV2MASTER
  assets/scss/_vars.scss
  assets/scss/newProject.scss
  assets/scss/projectDetails.scss
  composer.lock
  src/Controller/ProjectController.php
  src/DataFixtures/ProjectFeatureFixtures.php
  src/Repository/ProjectRepository.php
  src/Service/ProjectCalculator.php
  symfony.lock
  templates/feature/_form.html.twig
  templates/feature/edit.html.twig
  templates/project/_featureLine.html.twig
  templates/project/_featuresList.html.twig
  templates/project/_form.html.twig
  templates/project/edit.html.twig
  templates/project/index.html.twig
  templates/project/new.html.twig
  webpack.config.js
Labels: DEV 2 MASTER, reviewed

#72 S02US08
  src/Controller/FeatureController.php
  src/Controller/ProjectController.php
  src/DataFixtures/FeatureFixtures.php
  src/DataFixtures/ProjectFeatureFixtures.php
  src/Entity/Feature.php
  templates/project/_featuresList.html.twig
Labels: corrections done, reviewed

#92 S03 us27 users list
  config/packages/security.yaml
  src/Controller/UserController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  src/Form/UserType.php
  src/Repository/UserRepository.php
  templates/parts/_navbar.html.twig
  templates/user/_delete_form.html.twig
  templates/user/_form.html.twig
  templates/user/edit.html.twig
  templates/user/index.html.twig
  templates/user/new.html.twig
  templates/user/show.html.twig
Labels: corrections done, reviewed

#94 S03 us44 pagination project list
  assets/scss/_paginator.scss
  assets/scss/app.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/knp_paginator.yml
  config/packages/twig.yaml
  docker-entry.sh
  src/Controller/ProjectController.php
  symfony.lock
  templates/project/index.html.twig
  translations/KnpPaginatorBundle.fr.yml
Labels: corrections done, reviewed

#96 S03Fix_returnRouteAfterProjectEdit
  src/Controller/ProjectController.php
Labels: Fix, reviewed

#102 S03 us45 pagination features list
  src/Controller/FeatureController.php
  templates/feature/index.html.twig
Labels: reviewed

#125 DEV2MASTER
  assets/scss/_paginator.scss
  assets/scss/app.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/knp_paginator.yml
  config/packages/security.yaml
  config/packages/twig.yaml
  src/Controller/FeatureController.php
  src/Controller/ProjectController.php
  src/Controller/UserController.php
  src/DataFixtures/FeatureFixtures.php
  src/DataFixtures/ProjectFeatureFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Feature.php
  src/Entity/User.php
  src/Form/UserType.php
  src/Repository/UserRepository.php
  symfony.lock
  templates/feature/index.html.twig
  templates/parts/_navbar.html.twig
  templates/project/_featuresList.html.twig
  templates/project/index.html.twig
  templates/user/_delete_form.html.twig
  templates/user/_form.html.twig
  templates/user/edit.html.twig
  templates/user/index.html.twig
  templates/user/new.html.twig
  templates/user/show.html.twig
  translations/KnpPaginatorBundle.fr.yml
Labels: DEV 2 MASTER, reviewed

#93 S03Fix_ProjectFeatureFixtureCodeFactorisation
  src/DataFixtures/ProjectFeatureFixtures.php
Labels: ImportantFix, corrections done, reviewed

#127 S03US29_delete_user
  src/Controller/UserController.php
  templates/user/_delete_form.html.twig
  templates/user/index.html.twig
Labels: reviewed

#95 S03Fix_ExceptionsWhenAddingProjects
  assets/scss/app.scss
  src/Controller/ProjectController.php
  src/Form/ProjectType.php
  templates/feature/_form.html.twig
  templates/project/_featuresList.html.twig
  templates/project/_form.html.twig
Labels: ImportantFix, corrections done, reviewed

#109 S03 us28 create user
  assets/scss/user.scss
  config/packages/twig.yaml
  src/Controller/UserController.php
  src/Entity/User.php
  src/Form/UserType.php
  templates/base.html.twig
  templates/user/_form.html.twig
  templates/user/index.html.twig
  templates/user/new.html.twig
  webpack.config.js
Labels: corrections done, reviewed

#128 DEV2MASTER
  assets/scss/app.scss
  assets/scss/user.scss
  config/packages/twig.yaml
  src/Controller/ProjectController.php
  src/Controller/UserController.php
  src/DataFixtures/ProjectFeatureFixtures.php
  src/Entity/User.php
  src/Form/ProjectType.php
  src/Form/UserType.php
  templates/base.html.twig
  templates/feature/_form.html.twig
  templates/project/_featuresList.html.twig
  templates/project/_form.html.twig
  templates/user/_delete_form.html.twig
  templates/user/_form.html.twig
  templates/user/index.html.twig
  templates/user/new.html.twig
  webpack.config.js
Labels: DEV 2 MASTER, reviewed

#131 S03US14
  src/Controller/ProjectController.php
  src/Entity/ProjectFeature.php
  src/Form/ProjectType.php
  src/Repository/ProjectFeatureRepository.php
  src/Repository/ProjectRepository.php
  src/Service/ProjectCalculator.php
  templates/project/_featuresList.html.twig
  templates/project/_form.html.twig
Labels: corrections done, reviewed

#136 S05US46_pagination_user_list
  src/Controller/UserController.php
  templates/user/index.html.twig
Labels: reviewed

#137 S03US49_Load estimation according to price variant
  config/packages/twig.yaml
  src/Controller/ProjectController.php
  src/DataFixtures/ProjectFeatureFixtures.php
  src/Service/ProjectCalculator.php
Labels: reviewed

#132 S03 us50 user password
  assets/img/lock.png
  assets/js/security.js
  assets/scss/_vars.scss
  assets/scss/security.scss
  package.json
  src/Controller/ChangePasswordController.php
  src/Controller/UserController.php
  src/Entity/User.php
  src/Form/ChangePasswordType.php
  src/Form/UserType.php
  src/Repository/UserRepository.php
  src/Service/MailManager.php
  templates/security/changepassword.html.twig
  templates/security/security.html.twig
  templates/user/_form.html.twig
  templates/user/notification/notification.html.twig
  webpack.config.js
  yarn.lock
Labels: reviewed

#138 S03US48_Detelete feature on the selected variant
  src/Controller/ProjectController.php
  src/Service/ProjectCalculator.php
  templates/project/_featureLine.html.twig
Labels: corrections done, question, reviewed
