Repository WildCodeSchool/orleans-php-2003-project-easterapp, pull requests merged in 2020-07, with the labels that each got.

#157 fixed inversedBy
  src/Entity/Feature.php
Labels: reviewed

#158 S05US52_form_features_on_detail_project
  src/Controller/ProjectController.php
  src/Form/FeatureType.php
  templates/project/_addFeatures.html.twig
  templates/project/_form.html.twig
  templates/project/edit.html.twig
Labels: reviewed

#159 fix_user_create_form_display
  templates/security/changepassword.html.twig
  templates/user/new.html.twig
Labels: reviewed

#154 S03US47_Add new feature on the selected project variant
  src/Controller/ProjectController.php
  src/Form/SpecificFeatureType.php
  templates/feature/_form.html.twig
Labels: reviewed

#162 Dev2master
  assets/img/lock.png
  assets/js/security.js
  assets/scss/_vars.scss
  assets/scss/security.scss
  config/packages/twig.yaml
  package.json
  src/Controller/ChangePasswordController.php
  src/Controller/ProjectController.php
  src/Controller/UserController.php
  src/DataFixtures/ProjectFeatureFixtures.php
  src/Entity/Feature.php
  src/Entity/ProjectFeature.php
  src/Entity/User.php
  src/Form/ChangePasswordType.php
  src/Form/FeatureType.php
  src/Form/ProjectType.php
  src/Form/SpecificFeatureType.php
  src/Form/UserType.php
  src/Repository/ProjectFeatureRepository.php
  src/Repository/ProjectRepository.php
  src/Repository/UserRepository.php
  src/Service/MailManager.php
  src/Service/ProjectCalculator.php
  templates/feature/_form.html.twig
  templates/project/_addFeatures.html.twig
  templates/project/_featureLine.html.twig
  templates/project/_featuresList.html.twig
  templates/project/_form.html.twig
  templates/project/edit.html.twig
  templates/security/changepassword.html.twig
  templates/security/security.html.twig
  templates/user/_form.html.twig
  templates/user/index.html.twig
  templates/user/new.html.twig
  templates/user/notification/notification.html.twig
  webpack.config.js
  yarn.lock
Labels: DEV 2 MASTER, reviewed

#155 S05 us53 update user
  src/Controller/UserController.php
  src/Entity/User.php
  src/Form/ChangeRoleType.php
  templates/user/edit.html.twig
  templates/user/index.html.twig
Labels: corrections done, reviewed

#163 DesignFix_Select css updated to look as a select object
  assets/scss/_vars.scss
  assets/scss/projectDetails.scss
  templates/project/_form.html.twig
Labels: Fix, reviewed

#164 Fix: config mailer with gmail
  .env
  composer.json
  composer.lock
  symfony.lock
Labels: reviewed

#156 S05 us26 user connection
  assets/js/security.js
  config/packages/security.yaml
  src/Controller/HomeController.php
  src/Controller/ProjectController.php
  src/Controller/SecurityController.php
  src/Security/LoginFormAuthenticator.php
  templates/feature/edit.html.twig
  templates/home/index.html.twig
  templates/parts/_navbar.html.twig
  templates/project/index.html.twig
  templates/security/login.html.twig
Labels: corrections done, reviewed

#161 S05US15_default_quotation
  assets/scss/_vars.scss
  assets/scss/projectDetails.scss
  src/Controller/ProjectController.php
  src/DataFixtures/ProjectFixtures.php
  src/DataFixtures/QuotationFixtures.php
  src/Entity/Project.php
  src/Entity/Quotation.php
  src/Form/ProjectType.php
  src/Repository/QuotationRepository.php
  src/Service/ProjectCalculator.php
  templates/project/_form.html.twig
Labels: corrections done, reviewed

#180 Fix_create_user_mail
  config/services.yaml
  src/Controller/UserController.php
Labels: reviewed

#182 S06US16_feature_recurring
  src/Form/FeatureType.php
  src/Form/ProjectFeatureType.php
Labels: reviewed

#183 S05US52_show_price
  src/Controller/ProjectController.php
  templates/project/_form.html.twig
Labels: corrections done, reviewed

#192 Fix us16_resolved_bug_feature
  assets/scss/projectDetails.scss
  composer.lock
  src/Controller/ProjectController.php
  src/Form/FeatureType.php
  templates/project/_form.html.twig
Labels: ImportantFix, reviewed

#191 S06 us30 user profile
  assets/img/default_profile_picture.png
  assets/scss/profile.scss
  src/Controller/ProfileController.php
  src/Entity/User.php
  src/Form/UserUpdateType.php
  templates/parts/_navbar.html.twig
  templates/security/profile.html.twig
  templates/security/profilepassword.html.twig
  webpack.config.js
Labels: corrections done, reviewed

#193 Fix: error variable load and price_per_day on new project
  src/Controller/ProjectController.php
Labels: reviewed

#194 fix_choice_user_role
  src/Entity/User.php
  templates/user/index.html.twig
Labels: question

#196 Fix_SelectCSS
  assets/scss/projectDetails.scss
  templates/project/_form.html.twig
Labels: reviewed

#197 S06 us35 update user avatar
  assets/scss/profile.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/vich_uploader.yaml
  config/services.yaml
  public/uploads/.gitignore
  src/Controller/ProfileController.php
  src/Entity/User.php
  src/Form/AvatarUpdateType.php
  symfony.lock
  templates/security/profile.html.twig
Labels: corrections done, reviewed

#199 fix messages flash on features
  src/Controller/FeatureController.php
Labels: reviewed

#195 S06US17_projectIndexFigures
  assets/js/app.js
  assets/scss/_vars.scss
  assets/scss/app.scss
  src/Controller/ProjectController.php
  src/Service/ProjectCalculator.php
  symfony.lock
  templates/project/index.html.twig
Labels: corrections done, reviewed

#200 S06US13-projectSynthesis
  src/Controller/ProjectController.php
  src/Repository/ProjectRepository.php
  src/Service/ProjectCalculator.php
  templates/project/_featureLine.html.twig
  templates/project/_featuresList.html.twig
Labels: corrections done, reviewed

#204 S06 category
  assets/scss/category.scss
  config/packages/security.yaml
  src/Controller/CategoryController.php
  src/Entity/Category.php
  src/Form/CategoryType.php
  templates/category/_delete_form.html.twig
  templates/category/_form.html.twig
  templates/category/edit.html.twig
  templates/category/index.html.twig
  templates/category/new.html.twig
  templates/parts/_navbar.html.twig
  webpack.config.js
Labels: corrections done, reviewed

#205 S06US05_ProjectSorting
  src/Controller/ProjectController.php
  templates/project/index.html.twig
Labels: corrections done, reviewed

#206 S06 us36 pdf
  composer.json
  composer.lock
  src/Controller/ExportController.php
  src/Service/ProjectCalculator.php
  symfony.lock
  templates/export/export.html.twig
  templates/project/_form.html.twig
Labels: reviewed

#210 DEV2MASTER
  assets/scss/category.scss
  composer.json
  composer.lock
  config/packages/security.yaml
  src/Controller/CategoryController.php
  src/Controller/ExportController.php
  src/Controller/ProjectController.php
  src/Entity/Category.php
  src/Form/CategoryType.php
  src/Repository/ProjectRepository.php
  src/Service/ProjectCalculator.php
  symfony.lock
  templates/category/_delete_form.html.twig
  templates/category/_form.html.twig
  templates/category/edit.html.twig
  templates/category/index.html.twig
  templates/category/new.html.twig
  templates/export/export.html.twig
  templates/parts/_navbar.html.twig
  templates/project/_featureLine.html.twig
  templates/project/_featuresList.html.twig
  templates/project/_form.html.twig
  templates/project/index.html.twig
  webpack.config.js
Labels: DEV 2 MASTER, reviewed

#207 Fix user
  src/Controller/UserController.php
  templates/user/_delete_form.html.twig
  templates/user/_form.html.twig
  templates/user/edit.html.twig
  templates/user/index.html.twig
  templates/user/new.html.twig
  templates/user/show.html.twig
Labels: corrections done

#208 Fix Button Style
  templates/category/index.html.twig
  templates/feature/_delete_form.html.twig
  templates/feature/edit.html.twig
  templates/feature/index.html.twig
  templates/project/index.html.twig
Labels: corrections done, reviewed

#211 S06US51_sortingFeaturesList
  src/Controller/FeatureController.php
  src/Controller/ProjectController.php
  templates/feature/index.html.twig
Labels: reviewed

#209 S06_FixTableCss
  assets/scss/_vars.scss
  assets/scss/app.scss
  assets/scss/newProject.scss
  assets/scss/projectDetails.scss
  assets/scss/projectIndex.scss
  src/Controller/ProjectController.php
  src/DataFixtures/ProjectFixtures.php
  symfony.lock
  templates/category/index.html.twig
  templates/export/export.html.twig
  templates/feature/index.html.twig
  templates/project/_featureLine.html.twig
  templates/project/_featuresList.html.twig
  templates/project/_form.html.twig
  templates/project/index.html.twig
  templates/user/index.html.twig
  webpack.config.js
Labels: corrections done, reviewed

#213 fix_user_fixture_message
  src/Controller/SecurityController.php
  src/DataFixtures/UserFixtures.php
  src/Security/LoginFormAuthenticator.php
Labels: Fix, reviewed

#202 S03 us16 autocomplete list feature
  assets/js/app.js
  assets/js/easyautocomplete.js
  assets/scss/easyAutocomplete.scss
  composer.json
  package.json
  src/Controller/ProjectController.php
  src/Entity/Feature.php
  src/Form/FeatureType.php
  src/Form/SpecificFeatureType.php
  src/Repository/FeatureRepository.php
  templates/project/_addFeatures.html.twig
  templates/project/_form.html.twig
  templates/project/edit.html.twig
  webpack.config.js
  yarn.lock
Labels: corrections done, reviewed

#212 fix add project (was broken)
  templates/project/_form.html.twig
Labels: corrections done

#214 fix_category_new
  src/Form/CategoryType.php
Labels: reviewed

#215 dev 2 master
  assets/js/app.js
  assets/js/easyautocomplete.js
  assets/scss/_vars.scss
  assets/scss/app.scss
  assets/scss/easyAutocomplete.scss
  assets/scss/newProject.scss
  assets/scss/projectDetails.scss
  assets/scss/projectIndex.scss
  composer.json
  package.json
  src/Controller/FeatureController.php
  src/Controller/ProjectController.php
  src/Controller/SecurityController.php
  src/Controller/UserController.php
  src/DataFixtures/ProjectFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Feature.php
  src/Form/CategoryType.php
  src/Form/FeatureType.php
  src/Form/SpecificFeatureType.php
  src/Repository/FeatureRepository.php
  src/Security/LoginFormAuthenticator.php
  symfony.lock
  templates/category/index.html.twig
  templates/export/export.html.twig
  templates/feature/_delete_form.html.twig
  templates/feature/edit.html.twig
  templates/feature/index.html.twig
  templates/project/_addFeatures.html.twig
  templates/project/_featureLine.html.twig
  templates/project/_featuresList.html.twig
  templates/project/_form.html.twig
  templates/project/edit.html.twig
  templates/project/index.html.twig
  templates/user/_delete_form.html.twig
  templates/user/_form.html.twig
  templates/user/edit.html.twig
  templates/user/index.html.twig
  templates/user/new.html.twig
  templates/user/show.html.twig
  webpack.config.js
  yarn.lock
Labels: DEV 2 MASTER, reviewed

#216 Update README.md
  README.md
Labels: reviewed

#217 S06 fix project header
  assets/scss/_vars.scss
  assets/scss/app.scss
  assets/scss/projectDetails.scss
  src/DataFixtures/ApplicationFixtures.php
  src/Entity/Quotation.php
  src/Form/ProjectType.php
  templates/project/_addFeatures.html.twig
  templates/project/_featureLine.html.twig
  templates/project/_featuresList.html.twig
  templates/project/_form.html.twig
  templates/project/_projectHeader.html.twig
  templates/project/edit.html.twig
Labels: reviewed

#218 Add a troubleshooting paragraph into the readme file
  README.md
Labels: reviewed

#219 Fix_custom_page_404
  assets/scss/errors.scss
  assets/scss/navbar.scss
  composer.json
  composer.lock
  config/bundles.php
  symfony.lock
  templates/bundles/TwigBundle/Exception/error404.html.twig
  webpack.config.js
Labels: corrections done, reviewed

#249 Fix_Profil_Email
  src/Entity/User.php
Labels: Fix, reviewed

#252 Fix user fixture
  src/DataFixtures/UserFixtures.php
Labels: Fix, reviewed

#274 Fix_#273_FeatureSortingKeysColor
  symfony.lock
  templates/feature/index.html.twig
Labels: Fix, reviewed

#275 Fix_#272_EmptyFeatureTableStyle
  templates/project/_featuresList.html.twig
Labels: Fix, reviewed

#276 Fix_#264_EmptyDescriptionBugWhenEditingAFeatureProject
  src/Entity/ProjectFeature.php
Labels: Fix, reviewed

#277 Fix_#256_ProjectListDefaultSorting
  src/Controller/ProjectController.php
Labels: Fix, reviewed

#279 FIX_Profil_Photo
  assets/scss/profile.scss
Labels: reviewed

#280 Fix_#222_EditBtnHeight
  assets/scss/projectIndex.scss
Labels: Fix, reviewed

#281 Fix_#254_envFileUpdate
  .env
Labels: reviewed

#282 Fix all buttons style
  templates/category/_form.html.twig
  templates/category/edit.html.twig
  templates/category/index.html.twig
  templates/category/new.html.twig
  templates/feature/_form.html.twig
  templates/feature/index.html.twig
  templates/project/index.html.twig
  templates/security/profile.html.twig
  templates/security/profilepassword.html.twig
  templates/user/edit.html.twig
  templates/user/index.html.twig
  templates/user/new.html.twig
Labels: Fix, reviewed

#284 FIX_Messages flash supression projets
  src/Controller/ProjectController.php
Labels: Fix, reviewed

#285 fix message erreur add features
  src/Entity/Feature.php
Labels: Fix, reviewed

#278 FIX_Profil_Image_Explication
  assets/scss/profile.scss
  src/Form/AvatarUpdateType.php
Labels: corrections done, reviewed

#283 Fix_#241_TotalCompetencesPercentage
  src/Controller/ProjectController.php
  src/Entity/Project.php
  templates/project/_projectHeader.html.twig
Labels: Fix, corrections done, reviewed

#286 Fix_NotBlankFeatureDescription
  src/Entity/Feature.php
Labels: Fix, reviewed

#290 Fix_#259_ToolTipHtml
  assets/scss/app.scss
  templates/feature/index.html.twig
  templates/project/index.html.twig
Labels: Fix, reviewed

#291 Fix sort categories
  src/Controller/CategoryController.php
  src/Form/FeatureType.php
  src/Form/ProjectFeatureType.php
Labels: Fix, reviewed

#292 Fix bug autocomplete Close #293
  assets/js/easyautocomplete.js
  src/Controller/ProjectController.php
Labels: Fix, reviewed

#294 Fix_#220 route translation
  src/Controller/CategoryController.php
  src/Controller/ExportController.php
  src/Controller/FeatureController.php
  src/Controller/PasswordController.php
  src/Controller/ProfileController.php
  src/Controller/ProjectController.php
  src/Controller/SecurityController.php
  src/Controller/UserController.php
Labels: Fix, reviewed

#297 Fix_#295_ProjectSelectedVariantAfterModification
  src/Controller/ProjectController.php
Labels: Fix, reviewed

#288 Fix_#245_BtnBorderRadius
  assets/scss/app.scss
  templates/category/index.html.twig
  templates/feature/index.html.twig
  templates/project/index.html.twig
  templates/user/index.html.twig
Labels: corrections done

#301 Fix_300_MissingSaveButton
  templates/project/_form.html.twig
Labels: reviewed

#302 Fix_Ajout/ edit projet (interface)
  assets/scss/app.scss
  assets/scss/projectDetails.scss
  templates/project/_projectHeader.html.twig
Labels: reviewed

#251 FIX_Profil_Form
  src/Entity/User.php
Labels: Fix, corrections done, reviewed

#303 fix charges float
  src/Entity/Feature.php
  src/Form/FeatureType.php
Labels: Fix, reviewed

#304 Fix_Delete_Category
  src/Controller/CategoryController.php
Labels: Fix, reviewed

#305 FIX_Profil_Image
  assets/js/uploadform.js
  assets/scss/profile.scss
  templates/security/profile.html.twig
  webpack.config.js
Labels: Fix, reviewed

#306 feature sorting keys colors solved again
  templates/feature/index.html.twig
Labels: Fix, reviewed

#308 fix message d'erreur upper
  assets/scss/app.scss
  templates/feature/_form.html.twig
Labels: Fix, reviewed

#310 Fix_Security
  config/packages/security.yaml
Labels: Fix, reviewed

#311 Fix_ChromeButtonAlignment
  assets/scss/app.scss
  templates/feature/_form.html.twig
Labels: Fix, reviewed

#312 Fix_255_favicon
  assets/img/favicon.ico
  templates/base.html.twig
Labels: Fix, reviewed

#314 now the new standard feature form error message is displayed on one line
  templates/feature/_form.html.twig
Labels: Fix, reviewed

#315 FIX_User_Modif
  src/Controller/UserController.php
  src/DataFixtures/UserFixtures.php
  templates/user/index.html.twig
Labels: Fix, reviewed

#299 obligation choice variant when add feature in project
  src/Controller/ProjectController.php
  src/Entity/ProjectFeature.php
Labels: corrections done, reviewed

#313 dev2master
  .env
  README.md
  assets/img/favicon.ico
  assets/js/easyautocomplete.js
  assets/js/uploadform.js
  assets/scss/_vars.scss
  assets/scss/app.scss
  assets/scss/errors.scss
  assets/scss/navbar.scss
  assets/scss/profile.scss
  assets/scss/projectDetails.scss
  assets/scss/projectIndex.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/security.yaml
  docker-entry.sh
  src/Controller/CategoryController.php
  src/Controller/ExportController.php
  src/Controller/FeatureController.php
  src/Controller/PasswordController.php
  src/Controller/ProfileController.php
  src/Controller/ProjectController.php
  src/Controller/SecurityController.php
  src/Controller/UserController.php
  src/DataFixtures/ApplicationFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Feature.php
  src/Entity/Project.php
  src/Entity/ProjectFeature.php
  src/Entity/Quotation.php
  src/Entity/User.php
  src/Form/AvatarUpdateType.php
  src/Form/FeatureType.php
  src/Form/ProjectFeatureType.php
  src/Form/ProjectType.php
  symfony.lock
  templates/base.html.twig
  templates/bundles/TwigBundle/Exception/error404.html.twig
  templates/category/_form.html.twig
  templates/category/edit.html.twig
  templates/category/index.html.twig
  templates/category/new.html.twig
  templates/feature/_form.html.twig
  templates/feature/index.html.twig
  templates/project/_addFeatures.html.twig
  templates/project/_featureLine.html.twig
  templates/project/_featuresList.html.twig
  templates/project/_form.html.twig
  templates/project/_projectHeader.html.twig
  templates/project/edit.html.twig
  templates/project/index.html.twig
  templates/security/profile.html.twig
  templates/security/profilepassword.html.twig
  templates/user/edit.html.twig
  templates/user/index.html.twig
  templates/user/new.html.twig
  webpack.config.js
Labels: DEV 2 MASTER, reviewed

#316 Error pages
  assets/scss/errors.scss
  templates/base.error.html.twig
  templates/bundles/TwigBundle/Exception/error403.html.twig
  templates/bundles/TwigBundle/Exception/error404.html.twig
  templates/bundles/TwigBundle/Exception/error405.html.twig
  templates/bundles/TwigBundle/Exception/error500.html.twig
Labels: reviewed

#317 Fix autocomplete critique duplicate feature
  src/Controller/ProjectController.php
  src/Repository/FeatureRepository.php
  templates/project/_addFeatures.html.twig
Labels: reviewed

#318 FIX_PDF
  assets/img/Black Copy.png
  assets/img/Points.svg
  assets/img/vagues.svg
  src/Controller/ExportController.php
  templates/export/export.html.twig
Labels: Fix, reviewed

#321 fix entrypoints navbar
  assets/scss/navbar.scss
  templates/parts/_navbar.html.twig
  webpack.config.js
Labels: Fix, reviewed

#325 typo fixed : MO i user avatar form, caté/egory in feature index and …
  src/Form/AvatarUpdateType.php
  templates/feature/index.html.twig
  templates/user/index.html.twig
Labels: reviewed

#320 Fix feature deletion when enter pressed
  assets/js/formEnterLocker.js
  templates/project/_form.html.twig
  templates/project/edit.html.twig
  webpack.config.js
Labels: Fix, corrections done, reviewed

#327 Update formEnterLocker.js
  assets/js/formEnterLocker.js
Labels: Fix, corrections done, reviewed

#326 Dev2Master
  assets/img/Black Copy.png
  assets/img/Points.svg
  assets/img/envelope.png
  assets/img/envelope.svg
  assets/img/lock.png
  assets/img/lock.svg
  assets/img/vagues.svg
  assets/js/formEnterLocker.js
  assets/scss/errors.scss
  assets/scss/navbar.scss
  assets/scss/projectDetails.scss
  assets/scss/security.scss
  src/Controller/ExportController.php
  src/Controller/PasswordController.php
  src/Controller/ProjectController.php
  src/Controller/SecurityController.php
  src/Form/AvatarUpdateType.php
  src/Form/ProjectType.php
  src/Migrations/Version20200720211945.php
  src/Repository/FeatureRepository.php
  templates/base.error.html.twig
  templates/bundles/TwigBundle/Exception/error403.html.twig
  templates/bundles/TwigBundle/Exception/error404.html.twig
  templates/bundles/TwigBundle/Exception/error405.html.twig
  templates/bundles/TwigBundle/Exception/error500.html.twig
  templates/export/export.html.twig
  templates/feature/index.html.twig
  templates/parts/_navbar.html.twig
  templates/project/_addFeatures.html.twig
  templates/project/_featureLine.html.twig
  templates/project/_form.html.twig
  templates/project/_projectHeader.html.twig
  templates/project/edit.html.twig
  templates/security/login.html.twig
  templates/security/password.html.twig
  templates/security/requestpassword.html.twig
  templates/security/security.html.twig
  templates/user/index.html.twig
  webpack.config.js
Labels: DEV 2 MASTER, reviewed

#328 FIX_W3C
  templates/project/_featureLine.html.twig
Labels: Fix, reviewed

#329 FIX PDF Img and Text
  assets/img/Points.png
  assets/img/Points.svg
  assets/img/vagues.png
  assets/img/vagues.svg
  src/Controller/ExportController.php
  templates/export/export.html.twig
Labels: Fix, reviewed

#330 now connected features are deleted when project feature is
  src/Entity/ProjectFeature.php
Labels: reviewed

#331 Unique feature name
  src/Controller/ProjectController.php
  src/DataFixtures/FeatureFixtures.php
  src/DataFixtures/ProjectFeatureFixtures.php
  src/Entity/Feature.php
  src/Entity/ProjectFeature.php
  src/Form/ProjectFeatureType.php
  src/Form/SpecificFeatureType.php
  src/Repository/ProjectFeatureRepository.php
  templates/project/_addFeatures.html.twig
  templates/project/_featureLine.html.twig
Labels: reviewed

#332 DEV2MASTER
  assets/img/Points.png
  assets/img/Points.svg
  assets/img/vagues.png
  assets/img/vagues.svg
  src/Controller/ExportController.php
  src/Controller/ProjectController.php
  src/DataFixtures/FeatureFixtures.php
  src/DataFixtures/ProjectFeatureFixtures.php
  src/Entity/Feature.php
  src/Entity/ProjectFeature.php
  src/Form/ProjectFeatureType.php
  src/Form/SpecificFeatureType.php
  src/Repository/ProjectFeatureRepository.php
  templates/export/export.html.twig
  templates/project/_addFeatures.html.twig
  templates/project/_featureLine.html.twig
Labels: DEV 2 MASTER, reviewed

#334 fix font dir pdf
  src/Controller/ExportController.php
Labels: Fix, reviewed

#333 Update README.md
  README.md
Labels: reviewed

#335 dev2master
  README.md
  src/Controller/ExportController.php
Labels: DEV 2 MASTER

#336 FIX FONT (si c'est possible de la dev2master directement c super cool merci)
  src/Controller/ExportController.php
Labels: reviewed

#337 de2master
  src/Controller/ExportController.php
Labels: reviewed

#338 PDF ONE SHOT
  templates/export/export.html.twig
Labels: reviewed

#339 dev2master
  templates/export/export.html.twig
Labels: reviewed
